import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from "next/router";


const Navbar = () => {
  // const location = useLocation();
  const router = useRouter();
  const [prevScrollPos, setPrevScrollPos] = useState(0);
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollPos = window.scrollY;

      // Agar scroll down hua, to navbar chhupa do, aur scroll up hua to dikhado
      if (prevScrollPos > currentScrollPos) {
        setVisible(true);
      } else {
        setVisible(false);
      }

      setPrevScrollPos(currentScrollPos);
    };

    window.addEventListener('scroll', handleScroll);

    // Cleanup event listener on component unmount
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [prevScrollPos]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className={visible ? 'visible' : 'hidden'}>
        <a href="#home" className="logo">
          <i className='bx bxs-movie'></i>Sanamio
        </a>
        <div className="bx bx-menu" id="menu-icon"></div>

        {/* <!-- menu  --> */}
        <ul className="navbar">
          <li><Link  href="/" className={router.pathname === "/" ? 'home-active' : ''}>Home</Link></li>
          <li><Link className={router.pathname === "/Trending" ? 'home-active' : ''} href="/Trending">Trending</Link></li>
          <li><Link href="/coming">Coming</Link></li>
          <li><Link href="/newsletter">Newsletter</Link></li>
        </ul>
        <a href="#" className="btn">Sign In</a>
      </header>
    </div>
  )
}

export default Navbar;
