// import React, { useEffect, useState  } from "react";
// import Head from "next/head";
// import Link from "next/link";
// import mongoose from "mongoose";
// import Anime from "../models/Anime";
// import Recommended from "./Recommended";
// import Image from "next/image";

// const Detail = ({animeD, anime , AllAnimeData}) => {
//   console.log({'anime': anime})


//   const [show, setShow] = useState("-webkit-box");
//   const [more, setMore] = useState("show more");
//   const myanime = anime

//   const animeData = animeD
//   const [hydrated, setHydrated] = useState(false);

//   useEffect(() => {
//     setHydrated(true);
//   }, []);


//   if (!hydrated) {
//     return null;
//   }

//   console.log(animeData);

//   const toggleShow = () => {
//     if (show == "-webkit-box") {
//       setShow("block");
//       setMore("less more")
//     } else {
//       setShow("-webkit-box");
//       setMore("show more")
//     }
//   };

//   const studioName = animeData && animeData.studios.edges.length > 0 
//     ? animeData.studios.edges[0].node.name 
//     : "Unknown";

//   return (
//     <div style={{ overflowX: "hidden" }}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <style>{`
//         .m-main-container::before{
//     content : "";
//     background:linear-gradient(0deg, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(${animeData.coverImage.extraLarge});
//     filter: blur(10px);
//     background-attachment: fixed;
//     background-repeat: no-repeat;
//     background-position: center;
//     background-size: 100% auto;
//     height: 100%;
//     position: absolute;
//     width: 100vw;
//     left: 0;
//   }
//     @media only screen and (max-width: 650px) {
//     .m-main-container::before {
//         background-size: 100% 100%;
//     }
// }
//         `}</style>
//       </Head>

//       <div
//         className="details-header"
//         style={{
//           background: `url(${animeData.bannerImage}) 50% / cover`,
//         }}
//       ></div>
//       <div className="m-main-container">
//         <div className="main-container">
//           <div className="detail-container">
//             <div className="detail-container-img">
//             <Image
//   src={animeData.coverImage.extraLarge}
//   alt="anime"
//   width={300} // Set the appropriate width for your layout
//   height={450} // Set the appropriate height for your layout
// />
//             </div>
//             <div className="data-in-container">
//               <div className="anchor-for-back-page">
//                 <ul className="anchor-elements-in-ul">
//                   <li className="anchor-to-main">
//                     <Link role="button" href={"/index"}>
//                       <span>Home</span>
//                     </Link>
//                   </li>
//                   <li className="active-page-tag">
//                     <span>{animeData.title.english}</span>
//                   </li>
//                 </ul>
//               </div>
//               <h1>
//                 <label>
//                   <strong>{animeData.title.english} Hindi Tamil Telugu</strong>
//                 </label>
//               </h1>
//               <div className="text-data">
//                 <div className="video-details">
//                   <ul className="list-v">
//                     <li className="list-els-v">
//                       <span>HD</span>
//                     </li>
//                     <li className="list-els-v">
//                       <i className="fas fa-closed-captioning mr-1 icon-sub-dub_"></i>
//                       <span>{animeData.episodes}</span>
//                     </li>
//                     <li className="list-els-v">
//                       <i className="fas fa-microphone mr-1 icon-sub-dub_"></i>
//                       <span>{animeData.episodes}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div className="video-data">
//                   <ul className="list-v-t">
//                     <li className="list-els-v-t-1">
//                       <span>{animeData?.format === "TV" ? "TVSeries" : "Movie"}</span>
//                     </li>
//                     <li className="list-els-v-t-2">{animeData.duration}min/epi</li>
//                   </ul>
//                 </div>
//               </div>
//               <div className="btn-data">
//                 <Link href={`/Watch-Now/${anime.slug}`}>
//                   <button className="button-watch-now">
//                     <i className="fa-regular fa-circle-play m-txt"></i>
//                     <span>Watch Now</span>
//                   </button>
//                 </Link>
//                 <button className="btn-watch-list">
//                   <i className="fa-solid fa-plus"></i>
//                   Watch List
//                 </button>
//               </div>
//               <div className="time-index">
//                 <i className="fa-solid fa-clock t-txt"></i>
//                 <span>Updated on {animeData.endDate.day}-{animeData.endDate.month}-{animeData.endDate.year}</span>
//               </div>
//             </div>
//           </div>
//           <div className="more-anime-info">
//             <div className="anime-desc-more">
//               <div className="anime-desc-more-text">
//                 <p className="desc-text" style={{ display: `${show}` }}>
//                   &nbsp;The {animeData.title.english}.
//                   <br />
//                   <br />
//                   <div
//       dangerouslySetInnerHTML={{ __html: animeData.description }}
//     />
//                 </p>
//                 <a onClick={toggleShow} className="show-more-btn">
//                   {more}
//                 </a>
//               </div>
//               <h1 className="anime-characters-txt">Anime Characters</h1>
//               <div className="anime-all-characters">

//               {animeData.characters.edges.map(({ node, role }) => (
//                   <div key={node.id} className="anime-char">
//                    <Image
//   src={node.image.large}
//   alt={node.name.full}
//   width={100}
//   height={150}
// />
//                     <div className="anime-char-data">
//                       <h4>{node.name.full}</h4>
//                       <span>{role}</span>
//                     </div>
//                   </div>
//                 ))}
//               </div>
//             </div>
//             <div className="anime-desc-two">
//               <p>
//                 <strong>&nbsp;&nbsp;More about this anime</strong>
//               </p>
//               <hr />
//               <span>
//                 Other names&nbsp;:&nbsp;{animeData.synonyms.join(", ")}
//               </span>
//               <br />
//               <span>
//                 <strong>Country&nbsp;:</strong>&nbsp;{animeData.countryOfOrigin}
//               </span>
//               <br />
//               <span>
//                 <strong>Studio&nbsp;:</strong>&nbsp;{studioName}
//               </span>
//               <br />
//               <span>Score&nbsp;:&nbsp;{animeData.averageScore}/100</span>
//               <br />
//               <span>Release&nbsp;:&nbsp;{animeData.startDate.year}-{animeData.startDate.month}-{animeData.startDate.day}</span>
//               <br />
//               <span>Aired&nbsp;:&nbsp;None</span>
//               <br />
//               <span>Duration&nbsp;:&nbsp;{animeData.duration}min/epi</span>
//               <br />
//               <span>
//                 <strong>Episodes&nbsp;:</strong>&nbsp;{animeData.episodes}
//               </span>
//               <br />
//               <span>Status&nbsp;:&nbsp;{animeData.status}</span>
//               <br />
//               <hr />
//               <div className="anime-genres">
//                 <span>
//                   <strong>Genres&nbsp;:</strong>&nbsp;
//                 </span>
//                 {animeData.genres.map((genre) => (
//                   <span key={genre} className="round-updated">
//                     <a>{genre}</a>
//                   </span>
//                 ))}
//                 <br />
//               </div>
//               <hr />
//             </div>
//           </div>
//         </div>
//       </div>
//       <div className="more-season-anime-container">
//         <span className="more-anime-txt">
//           <b>More Seasons of this Anime</b>
//         </span>
//         <div className="anime-more-season-data">
//           <Link
//             href={""}
//             className="anime-season-item"
//             style={{
//               background:
//                 "linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url(https://img.flawlessfiles.com/_r/100x200/100/a2/62/a26294497c6afa9b885636b373d611f9/a26294497c6afa9b885636b373d611f9.jpg)",
//               backgroundRepeat: "no-repeat",
//               backgroundPosition: "center",
//               backgroundSize: "100%",
//             }}
//           >
//             <div>
//               <h2>Jujutsu Kaisen 0: The Movie</h2>
//             </div>
//           </Link>
//           <Link
//             href={""}
//             className="anime-season-item"
//             style={{
//               background:
//                 "linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url(https://img.flawlessfiles.com/_r/100x200/100/82/40/82402f796b7d84d7071ab1e03ff7747a/82402f796b7d84d7071ab1e03ff7747a.jpg)",
//               backgroundRepeat: "no-repeat",
//               backgroundPosition: "center",
//               backgroundSize: "100%",
//             }}
//           >
//             <div>
//               <h2>Season 1</h2>
//             </div>
//           </Link>
//         </div>
//         <div className="anime-trailer">
//           <div className="trailer-txt">
//             <span className="more-anime-txt">
//               <b>Trailer</b>
//             </span>
//             <div>
//               <div className="trailer-vid">
//                 <iframe
//                   allowFullScreen="allowfullscreen"
//                   className="trailer-video"
//                   data-v-cc58dc40=""
//                   frameBorder="0"
//                   src={myanime?.trailer ? myanime.trailer : ""}
//                 ></iframe>
//               </div>
//             </div>
//           </div>
//         </div>
//       </div>
//         <Recommended AllAnimeData={AllAnimeData}/>
//     </div>
//   );
// };

// export default Detail;

// export async function getServerSideProps(context){

//    // get my anime data
//    if (!mongoose.connections[0].readyState) {
//     await mongoose.connect(process.env.MONGO_URI)
//   }

//   let anime = await Anime.findOne({ slug: context.query.slug });;
//   let MyAnime = await Anime.find({});

//   let animeId =  anime.id


//     // AniList API endpoint
//     const API_URL = "https://graphql.anilist.co";

//     // GraphQL querys to fetch anime details

//       const fetchAnimeData = async(id)=>{
//         // GraphQL query to fetch anime details
//         const query = `
//         query ($id: Int, $type: MediaType) {
//           Media(id: $id, type: $type) {
//               id
//               title {
//                 romaji
//                 english
//                 native
//               }
//               description
//               format
//               startDate {
//                 year
//                 month
//                 day
//               }
//               endDate {
//                 year
//                 month
//                 day
//               }
//               season
//               episodes
//               status
//               popularity
//               favourites
//               genres
//               synonyms
//               source
//               isAdult
//               bannerImage
//               countryOfOrigin
//               seasonYear
//               averageScore
//               duration
//               coverImage {
//                 extraLarge
//                 large
//                 medium
//                 color
//               }
//               studios {
//                 edges {
//                   node {
//                     name
//                   }
//                 }
//               }
//                 chapters
//                     relations {
//           edges {
//             node {
//              id
//               title {
//                 romaji
//                 english
//                 native
//               }
//                 coverImage {
//                 extraLarge
//                 large
//                 medium
//                 color
//               }
//             }
      
//             relationType
//           }
//         }
//           externalLinks {
//           site
//           url
//         }
//               characters {
//                 edges {
//                   node {
//                     id
//                     name {
//                       full
//                     }
//                     image {
//                       large
//                     }
//                   }
//                   role
//                 }
//               }
//             }
//           }
//       `;
      
//           // Variables for the query
//           const variables = {
//             id: id, // Replace with actual anime ID
//             type: "ANIME",
//           };
//           // Fetch options
//           const fetchOptions = {
//             method: "POST",
//             headers: {
//               "Content-Type": "application/json",
//               Authorization:
//                 `Bearer ${process.env.NEXT_PUBLIC_ACCESS_TOKEN}`, // Replace with actual access token
//             },
//             body: JSON.stringify({
//               query,
//               variables,
//             }),
//           };
       
//           try {
//             const response = await fetch(API_URL, fetchOptions);
//             const data = await response.json();
//             if (!response.ok) {
//               throw new Error(`Error fetching data for ID ${id}: ${data.message}`);
//             }
//             return data.data.Media;
//           } catch (error) {
//             console.error(error);
//             return null; // Returning null in case of error
//           }
//       }

//       const fetchPromises = fetchAnimeData(animeId)
//       const results = await (fetchPromises);


//       const fetchAllAnimeData = async (id) => {
//         const fetchOptions = {
//           method: "POST",
//           headers: {
//             "Content-Type": "application/json",
//             Authorization: `Bearer ${process.env.NEXT_PUBLIC_ACCESS_TOKEN}`, // Replace with actual access token
//           },
//           body: JSON.stringify({
//             query: `
//                       query ($id: Int, $type: MediaType) {
//                         Media(id: $id, type: $type) {
//                           id
//                           title {
//                             romaji
//                             english
//                             native
//                           }
//                           description
//                           episodes
//                           format
//                           seasonYear
//                           averageScore
//                           duration
//                           genres
//                           status
//                            startDate {
//                               year
//                               month
//                               day
//                             }
//                             endDate {
//                               year
//                               month
//                               day
//                             }
//                           coverImage {
//                                 extraLarge
//                                 large
//                                 medium
//                                 color
//                             }
//                         }
//                       }
//                     `,
//             variables: {
//               id: id,
//               type: "ANIME",
//             },
//           }),
//         };
    
//         try {
//           const response = await fetch(API_URL, fetchOptions);
//           const data = await response.json();
//           if (!response.ok) {
//             throw new Error(`Error fetching data for ID ${id}: ${data.message}`);
//           }
//           return data.data.Media;
//         } catch (error) {
//           console.error(error);
//           return null; // Returning null in case of error
//         }
//       };
//       const fetchAllAnime = MyAnime.map((id) => fetchAllAnimeData(id.id));
    
//       const Allresults = await Promise.all(fetchAllAnime);
    
//       const validResults = Allresults.filter((result) => result !== null);

//   return {
//     props: {animeD: results, anime: JSON.parse(JSON.stringify(anime)), AllAnimeData: validResults}
//   }
// }
