import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

const Watch = () => {
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <style>{`
        .watch-container::before{
        content : "";
        background:linear-gradient(0deg, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-yxY3olrjZH4k.png);
        filter: blur(10px);
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100% auto;
        height: 100%;
        position: absolute;
        width: 100vw;
        left: 0;
    }
    @media only screen and (max-width: 650px) {
    .watch-main-container::before {
        background-size: 100% 100%;
    }
}
        `}</style>
      </Head>
    <div className='watch-main-container' style={{overflowX: "hidden", marginBottom: "50px"}}>
        <div className="watch-container">
            <div className="main-contant">
            <div className="episode-video">
                <div className="video-player" style={{position: "static"}}>
                    {/* <div className="main-video-player">
                        <div className="video-wrapper">
                            <video src="" style={{width: "100%", height: "100%"}}></video>
                        </div>
                    </div> */}
                    <iframe src="https://swift.multiquality.click/embed/RrGrHXplrGiIibj" autoplay="1" id="video-player" class="video-player" allowFullScreen="allowFullScreen" allow="accelerometer;autoplay;encripted-media;gyroscope;picture-in-picture" webkitallowfullscreen="true" mozallowfullscreen="true" frameBorder="0" scrolling="no"></iframe>
                </div>
                <div className="episode-detail">
                    <div className="video-dow" style={{justifyContent: "end"}}>
                        <div className="video-dow-container">
                            <div className="video-dow-btns">
                                <div className="video prev-episode" style={{display: "none"}}>
                                    <div className="video-txt">
                                        <i className="fa-solid tiny-t fa-backward"></i>
                                        Prev
                                    </div>
                                </div>
                                <div className="video next-episode">
                                    <div className="video-txt">
                                        Next
                                        <i className="fa-solid tiny-t fa-forward"></i>
                                    </div>
                                </div>
                                <div className="video download">
                                    <div className="video-txt">
                                        <i className="fa-solid tiny-t fa-download"></i>
                                        Download
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="episode-desbord">
                        <div className="episode-numbar">
                            <span>You are Watching</span>
                            <p>
                            Episode-
                            <span>1</span>
                            <span className='filler-alert'></span>
                            </p>
                            <span>Switch Server if current server doesn't work.</span>
                        </div>
                        <div className="episode-servers">
                            <div className="episode-a">
                                <span className='text-in-episode-details'>वीडियो में 🎧 क्लिक करके हिंदी सेलेक्ट कारु </span>
                                <div className="episode-server-section">
                                    <div className="server-1">
                                        <div className="serv-txt">
                                            <span>Server 1 :</span>
                                        </div>
                                    </div>
                                        <div className="selact-servers">
                                            <div className="servers-div">
                                                <div className="server-btn">
                                                    <span>Vid Cloud</span>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div className="episode-server-section">
                                    <div className="server-1">
                                        <div className="serv-txt">
                                            <span>Server 2 :</span>
                                        </div>
                                    </div>
                                        <div className="selact-servers">
                                            <div className="servers-div">
                                                <div className="server-btn">
                                                    <span>Awesome Stream</span>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="episodes-container">
               <div className="header">
                <h2>Solo Leveling</h2>
                <div className="episodes-list-sec">
                    <div className='container-title'>
                        <span>List of episodes :</span>
                    </div>
                </div>
               </div>
               <div className="list-container">
                <div className="episodes-list">
                    <div className="content" style={{display: "grid", gridTemplateColumns: "100%", gridGap: "0 0"}}>
                        <div className="episode-short">
                            <div className="short-anime-ep">
                                <div className="episode-num active-episode episode-alternate-1">
                                    1
                                </div>
                                <div className="episode-name active-episode-2 episode-alternate-2">
                                    <span>If I had one more chance</span>
                                </div>
                            </div>
                        </div>
                        <div className="episode-short">
                            <div className="short-anime-ep">
                                <div className="episode-num episode-alternate-2">
                                    2
                                </div>
                                <div className="episode-name episode-alternate-1">
                                    <span>If I had one more chance</span>
                                </div>
                            </div>
                        </div>
                        <div className="episode-short">
                            <div className="short-anime-ep">
                                <div className="episode-num episode-alternate-1">
                                    3
                                </div>
                                <div className="episode-name episode-alternate-2">
                                    <span>If I had one more chance</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               </div>
            </div>
            </div>
            <div className="more-season-anime-container" style={{position: "relative" , zIndex: "10"}}>
        <span className="more-anime-txt">
          <b>More Seasons of this Anime</b>
        </span>
        <div className="anime-more-season-data">
          <Link
            href={""}
            className="anime-season-item"
            style={{
              background:
                "linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url(https://img.flawlessfiles.com/_r/100x200/100/a2/62/a26294497c6afa9b885636b373d611f9/a26294497c6afa9b885636b373d611f9.jpg)",
              backgroundRepeat: "no-repeat",
              backgroundPosition: "center",
              backgroundSize: "100%",
            }}
          >
            <div>
              <h2>Jujutsu Kaisen 0: The Movie</h2>
            </div>
          </Link>
          <Link
            href={""}
            className="anime-season-item"
            style={{
              background:
                "linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url(https://img.flawlessfiles.com/_r/100x200/100/82/40/82402f796b7d84d7071ab1e03ff7747a/82402f796b7d84d7071ab1e03ff7747a.jpg)",
              backgroundRepeat: "no-repeat",
              backgroundPosition: "center",
              backgroundSize: "100%",
            }}
          >
            <div>
              <h2>Season 1</h2>
            </div>
          </Link>
        </div>
      </div>
        </div>
    </div>
    </>
  )
}

export default Watch
